### ISSUE TITLE
Add this to bower

### ISSUE THREAD

**Issue by tadeucaldas** [255kb/overwatch-heroes-icon-font#6]
Could you place this into bower repository!?

**Comment by 255kb** [comment]
yeah why not, give me a few days and I'll do it :)

**Comment by tadeucaldas** [comment]
Tks man! here is a link that will help you

https://bower.io/docs/creating-packages/#register

**Comment by 255kb** [comment]
it's done 
package name: `overwatch-heroes-icon-font`
