### ISSUE TITLE
Add Orisa icon

### ISSUE THREAD

**Issue by danielmarquard** [255kb/overwatch-heroes-icon-font#7]
Hey @255kb,

I've got an Orisa icon for the Overwatch heroes font! Can you please add this to your repo? Thanks, [MissMadison](http://yoshinoyoshie.deviantart.com/), for the vector!

[orisa-icon-vector.zip](https://github.com/255kb/overwatch-heroes-icon-font/files/917190/orisa-icon-vector.zip)

**Comment by 255kb** [comment]
Thanks for the contribution and sorry for the looong delay, I updated the font with Orisa's icon. Under version 1.2.0
